// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"1920","changeWindowHeightTo":"1080","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"true","Custom Image":"Intro","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"GALV_BalloonSoundEffects","status":true,"description":"Set sound effects to play whenever balloons are shown above characters","parameters":{"Exclamation":"Flash1,80,150","Question":"Jump1,80,120","Music Note":"Up3,80,150","Heart":"Sound2,80,150","Anger":"Push,80,150","Sweat":"Miss,80,150","Cobweb":"Wind4,80,150","Silence":"","Light Bulb":"Load,80,150","Zzz":"","User-defined 1":"Item1,80,150","User-defined 2":"Item2,80,150","User-defined 3":"Item3,80,150","User-defined 4":"Reflection,80,150","User-defined 5":"Reflection,80,100"}}
];
